task :build do
  `cd src && zip -r delicious-domain-tags.xpi *`
  `mv src/delicious-domain-tags.xpi .`
  hash = `md5 delicious-domain-tags.xpi`[/= (.+)/, 1]
  installation_html_file = File.join(File.dirname(__FILE__), 'installation.html')
  installation_html = File.open(installation_html_file) { |f| f.read }
  installation_html.gsub!(/'md5:(.*)'/, "'md5:#{hash}'")
  File.open(installation_html_file, 'w') { |f| f.puts(installation_html) }
end