task :build do
  `ruby bin/generate_install_manifest.rb`
  `cd src && zip -r delicious-permalinks.xpi *`
  `mv src/delicious-permalinks.xpi public/`
  hash = `md5 public/delicious-permalinks.xpi`[/= (.+)/, 1]
  installation_html_file = File.join(File.dirname(__FILE__), 'public', 'installation.html')
  installation_html = File.open(installation_html_file) { |f| f.read }
  installation_html.gsub!(/'md5:(.*)'/, "'md5:#{hash}'")
  File.open(installation_html_file, 'w') { |f| f.puts(installation_html) }
end