INTERNET_BANKING_ID = 'YOUR_INTERNET_BANKING_ID'
DATE_OF_BIRTH = 'YOUR_DATE_OF_BIRTH'
SECURITY_CODE = 'YOUR_SECURITY_CODE'
SORT_CODE_AND_ACCOUNT_NUMBER = 'SORT_CODE_THEN_ACCOUNT_NUMBER_WITHOUT_SPACES'