class ApacheConfig
  def initialize(domain)
    @domain = domain
  end
  def filename
    "#{@domain}.conf"
  end
  def install_path
    File.join('/', 'etc', 'apache2', 'other', filename)
  end
end

namespace :apache do
  namespace :dev do

    desc "Create an Apache config file so that we can preview local changes to the blog."
    task :create_config do
      PROJECT_ROOT = File.dirname(__FILE__)

      domain = 'blog.seagul.dev'
      public_directory = File.expand_path(File.join(PROJECT_ROOT, 'public'))
      log_directory = File.expand_path(File.join(PROJECT_ROOT, 'log'))

      apache_config_template = File.join(PROJECT_ROOT, 'config', 'apache.config.erb')

      require File.join(PROJECT_ROOT, 'site-generation', 'lib', 'erb_renderer')

      apache_config = ApacheConfig.new(domain)
      renderer = ErbRenderer.new(apache_config_template, binding)
      File.open(apache_config.filename, 'w') { |f| renderer.render(f) }

      `sudo mv #{apache_config.filename} #{apache_config.install_path}`
    end

    desc "Remove the Apache config file for development"
    task :remove_config do
      apache_config = ApacheConfig.new('blog.seagul.dev')
      `sudo rm #{apache_config.install_path}`
    end
  
  end
end
