require File.join(File.dirname(__FILE__), 'firefox-extension.rb')

desc "Build the extension, i.e. zip up the content of src/ as a .xpi and move it to the the build directory"
task :build do
  config = YAML.load_file(File.join(EXTENSION_CONFIG_DIRECTORY, 'extension.yml'))
  
  `rm -rf #{EXTENSION_BUILD_DIRECTORY}`
  `mkdir #{EXTENSION_BUILD_DIRECTORY}`
  
  InstallManifest.generate(config, EXTENSION_SRC_DIRECTORY)
  filename = "#{config[:extension][:filename]}-without-update-url.xpi"
  `cd #{EXTENSION_SRC_DIRECTORY} && zip -r #{filename} *`
  `mv #{File.join(EXTENSION_SRC_DIRECTORY, filename)} #{EXTENSION_BUILD_DIRECTORY}`
  
  InstallManifest.generate(config, EXTENSION_SRC_DIRECTORY, include_update_url = true)
  filename = "#{config[:extension][:filename]}.xpi"
  `cd #{EXTENSION_SRC_DIRECTORY} && zip -r #{filename} *`
  `mv #{File.join(EXTENSION_SRC_DIRECTORY, filename)} #{EXTENSION_BUILD_DIRECTORY}`
  
  UpdateManifest.generate(config, EXTENSION_BUILD_DIRECTORY)
  filename = "#{config[:extension][:filename]}-update.rdf"
  `mv #{File.join(EXTENSION_BUILD_DIRECTORY, 'update.rdf')} #{File.join(EXTENSION_BUILD_DIRECTORY, filename)}`
end